metadata:
  favicon: ''
  code: "<style>\n  .clickable nb-card {\n    cursor: pointer;\n  }\n  \n  .clickable nb-card:hover {\n  \tbackground-color: #E8EEFB;\n  }\n  \n  .no-border nb-card {\n    border: none;\n  }\n  \n  .no-border .form-content {\n    padding: 0;\n  }\n  \n  ub-horizontal-menu a[nbButton].active {\n    background-color: rgb(69 112 246 / 37%)!important;\n  }\n  \n  ub-horizontal-menu a[nbButton]:hover {\n    background-color: rgb(69 112 246 / 37%)!important;\n  }\n  \n  .small-metric nb-card-body {\n    padding-top: 0!important;\n  }\n  \n  .no-shadow button {\n    filter: none!important;\n  }\n</style>"
  title: New app
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 1
  density: compact
internalType: project
